[CI]updated drone.star file
owncloud/activity pull request #1073
Opened 2022-03-10 08:47 UTC by sushmita56

## Description
This is an update on drones.star file 
- using drone-cancel-previous-builds
- using thegeeklab/drone-github-comment instead of jmccann/drone-github-comment for github comments 
- moving docker image references to constants
- using caches images

## Related Issue
- Part of issue: 
- https://github.com/owncloud/QA/issues/700
- https://github.com/owncloud/QA/issues/717
- https://github.com/owncloud/QA/issues/729
- https://github.com/owncloud/QA/issues/728

2022-03-10 08:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/activity?pullRequest=1073) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/activity?pullRequest=1073) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/activity?pullRequest=1073) it.</sub>

2022-03-10 09:33 UTC, kiranparajuli589 requested changes

2022-03-10 09:33 UTC, kiranparajuli589 commented on .drone.star
> -                        "pull": "always",
afaik, pull should be now `if-not-exists` to use cache.

2022-03-10 09:33 UTC, kiranparajuli589 commented on .drone.star
> +        "image": OC - CI_CEPH_UBUNTU,
```suggestion
        "image": CI_CEPH_UBUNTU,
```

2022-03-10 09:33 UTC, kiranparajuli589 commented on .drone.star
> +                                 "image": OC_CI_PHP + ":%s" % phpVersion,
do not add ':%s' in every usage, you can include it in the `OC_CI_PHP` var itself and then just do:
```suggestion
                                 "image": OC_CI_PHP % phpVersion,
```

2022-03-10 09:35 UTC, kiranparajuli589 requested changes

2022-03-10 09:35 UTC, kiranparajuli589 commented on .drone.star
> +OC_CI_ALPINE_LATEST = "owncloudci/alpine:latest"
imo, the existing name is good. also the same is used all over other apps, so best not to rename

2022-03-10 11:57 UTC, kiranparajuli589 requested changes
few more improvements to be made:

2022-03-10 11:57 UTC, kiranparajuli589 commented on .drone.star
> +                        "image": OC_CI_PHP % "7.4",
`DEFAULT_PHP_VERSION` can be used

2022-03-10 11:57 UTC, kiranparajuli589 commented on .drone.star
> +                                     "image": OC_CI_PHP % testConfig["phpVersion"],
use DEFAULT_PHP_VERSION

2022-03-10 11:57 UTC, kiranparajuli589 commented on .drone.star
> +        "image": OC_CI_ELASTIC_SEARCH + "%s" % esVersion,
```suggestion
        "image": OC_CI_ELASTIC_SEARCH % esVersion,
```
manage `%s` from the declaration.

2022-03-10 11:57 UTC, kiranparajuli589 commented on .drone.star
> +            "image": OC_CI_PHP % esVersion,
```suggestion
            "image": DEFAULT_PHP_VERSION,
```

2022-03-10 18:45 UTC, grgprarup commented on .drone.star
> +AWS_CLI = "banst/awscli"
```suggestion
BANST_AWS_CLI = "banst/awscli"
```

2022-03-10 18:46 UTC, grgprarup commented on .drone.star
> +OC_CI_ELASTIC_SEARCH = "owncloudops/elasticsearch"
```suggestion
OC_OPS_ELASTIC_SEARCH = "owncloudops/elasticsearch"
```

2022-03-10 18:47 UTC, grgprarup commented on .drone.star
> +OC_CI_ORACLE = "owncloudci/oracle-xe:latest"
```suggestion
OC_CI_ORACLE_XE = "owncloudci/oracle-xe:latest"
```

2022-03-10 18:47 UTC, grgprarup commented on .drone.star
> +OPEN_LDAP = "osixia/openldap"
```suggestion
OSIXIA_OPEN_LDAP = "osixia/openldap"
```

2022-03-10 18:56 UTC, grgprarup reviewed
It will be good practice to use the same name for constants throughout all app repos. Also, sort the constants alphabetically.
Note: Make other necessary changes for the suggested change

2022-03-11 06:48 UTC, phil-davis commented
> It will be good practice to use the same name for constants throughout all app repos.

The existing constants and code are identical in almost all oC10 app repos. We must keep it that way. (There are some oC10 app repos with extra code - maybe user_ldap is the only one)

We need to do the functional code and constants changes in the activity app, and then copy to all other apps. We don't want people to design a slightly-different solution in each app.

2022-03-11 08:07 UTC, amrita-shrestha commented on .drone.star
> -                        "pull": "always",
@sushmita56

2022-03-11 08:08 UTC, amrita-shrestha commented on .drone.star
> -                "pull": "always",
pull should be now if-not-exists to use cache.

2022-03-11 08:26 UTC, amrita-shrestha commented on .drone.star
> +                        "image": OC_CI_PHP % "7.4",
@kiranparajuli589 dai can you clear me why we are using
 `"image": OC_CI_PHP % "7.4",` 
and `"image": OC_CI_PHP % phpVersion`
in all phpVersion we have 7.4 .
what is use of making it so much complex.If we using same php version

2022-03-11 08:49 UTC, amrita-shrestha commented
> It will be good practice to use the same name for constants throughout all app repos. Also, sort the constants alphabetically. Note: Make other necessary changes for the suggested change

@grgprarup I think we should first discuss this ordering alphabetically or any other way at first.

2022-03-11 08:56 UTC, sushmita56 commented on .drone.star
> -                        "pull": "always",
@amrita-shrestha It was resolved by @grgprarup him, not me

2022-03-11 08:59 UTC, grgprarup commented on .drone.star
> +                        "image": OC_CI_PHP % "7.4",
> > It will be good practice to use the same name for constants throughout all app repos. Also, sort the constants alphabetically. Note: Make other necessary changes for the suggested change
> 
> @grgprarup I think we should first discuss this ordering alphabetically or any other way at first in the group because others are also involved in the same issue.

IMO it will be easy to manage and search for used constants if placed alphabetically. Though it does not affect in code efficiency and functionality.

2022-03-11 09:01 UTC, kiranparajuli589 commented on .drone.star
> +                        "image": OC_CI_PHP % "7.4",
we can provide more PHP versions through the config dict. if nothing is provided then some default is used.
```
default = {
"phpVersions": ["7.4", "8.0", "7.2", "7.3"],
}
```
the approach seems reasonable to me.

2022-03-11 09:02 UTC, grgprarup commented on .drone.star
> -                "pull": "always",
@amrita-shrestha by default it will use `if-not-exists`, so we discussed to remove `"pull": "always"` if `"pull": "always"` exist.

2022-03-11 09:03 UTC, sushmita56 commented on .drone.star
> -                        "pull": "always",
And the suggested changes have been made already. Let me know if other changes are required.

2022-03-11 09:05 UTC, grgprarup commented
> > It will be good practice to use the same name for constants throughout all app repos. Also, sort the constants alphabetically. Note: Make other necessary changes for the suggested change
> 
> @grgprarup I think we should first discuss this ordering alphabetically or any other way at first in the group because others are also involved in the same issue.

IMO it will be easy to manage and search for used constants if placed alphabetically. Though it does not affect in code efficiency and functionality.

2022-03-14 03:29 UTC, SagarGi commented on .drone.star
> +DEFAULT_PHP_VERSION = "owncloudci/php:7.4"
@sushmita56 move this to up in ascending order

2022-03-14 05:55 UTC, sushmita56 commented on .drone.star
> +                                     "image": OC_CI_PHP % testConfig["phpVersion"],
The `phpversion` here comes from `testConfig`. So I think it is better not to use `DEFAULT_PHP_VERSION`.

2022-03-14 07:36 UTC, amrita-shrestha submitted a review, later dismissed

2022-03-14 07:36 UTC, amrita-shrestha commented on .drone.star
>                  "message_file": "%s/comments.file" % dir["base"],
check how it is implemented in ocis https://github.com/owncloud/ocis/blob/master/.drone.star#L809

2022-03-14 11:09 UTC, phil-davis commented on .drone.star
>                  "message_file": "%s/comments.file" % dir["base"],
IMO this is the only thing that needs looking into for this PR.
Need to look into what ends up in comments.file here, and if `thegeeklab/drone-github-comment` supports `message_file`

And add "update" and "api_key" settings, and remove the GITHUB_TOKEN environment variable.

@sushmita56 if you like, you can change `thegeeklab` back to `jmccann` in this PR, and we can get it merged. Then do this change in a next PR.

2022-03-15 05:06 UTC, kiranparajuli589 commented on .drone.star
> -                             ] + testConfig["extraTeardown"] + buildGithubCommentForBuildStopped(name, params["earlyFail"]) + githubComment(params["earlyFail"]) + stopBuild(ctx, params["earlyFail"]),
why removing `buildGithubCommentForBuildStopped` from here?

2022-03-15 05:25 UTC, phil-davis commented
PR #1088 demonstrates an acceptance test fail that reports to the PR on GitHub. It works - good.

2022-03-15 05:30 UTC, phil-davis commented on .drone.star
> -                             ] + testConfig["extraTeardown"] + buildGithubCommentForBuildStopped(name, params["earlyFail"]) + githubComment(params["earlyFail"]) + stopBuild(ctx, params["earlyFail"]),
That step wrote a comment into `comments.file` and jmccann/drone-github-comment posted the file content to a GitHub comment.

The new `thegeeklab/drone-github-comment` puts the comment content directly in-line as the "message" parameter. So there is no need to create `comments.file`

2022-03-15 05:31 UTC, phil-davis approved these changes
LGTM

2022-03-15 05:32 UTC, phil-davis commented
@amrita-shrestha @kiranparajuli589 please review again. We can merge if everyone is happy.

2022-03-15 06:00 UTC, kiranparajuli589 approved these changes

2022-03-15 06:02 UTC, merged

2022-03-15 07:46 UTC, amrita-shrestha commented on .drone.star
> +OC_OPS_ELASTIC_SEARCH = "owncloudops/elasticsearch:%s"
Is this in alphabetical order?